### ISSUE TITLE
Upload of connectivity matrices based on Test data resulting from AIDAmri

### ISSUE THREAD

**Issue by THinnerichs** [aswendtlab/AIDAconnect#2]
Hey there,

I am currently trying to get your pipeline from `AIDAmri` to work using NiftyReg and FSL in order to use `AIDAconnect`. However, as both have poor documentation and some deprecation issues, would it be possible to upload the results of your pipeline based on your test data? 

If I am not mistaken this should output a matrix measuring e.g. functional connectivity of structures defined within Allen Mouse Brain Atlas? 

Thank you very much in advance!

**Comment by aswendtlab-admin** [comment]
Hi Tilman, 
not satisfied with the manual or code? We are always open for contributors!
The matrix is loaded by AIDAconnect/fMRI/rsfMRI_Processing/getMergedFMRI_data.m: matFile_cur = dir([cur_path '/*/fMRI/regr/MasksTCsSplit*txt.mat']); the test data contains everything needed to run AIDAconnect.

**Comment by THinnerichs** [comment]
Hey,
Thank you very much for the quick reply!

Your documentation seems to work great, but e.g. FSL and NiftyReg docs need time to get used to. Maybe substitute the NiftyReg section using an approach similar to [RNiftyReg[(https://github.com/jonclayden/RNiftyReg)? For FSL maybe link to the source code directly in order to compile from source. Or link to the precompiled binaries directly. :) 

Concerning the connectivity matrix: 
If I just want to download the structural (dMRI) and functional (fMRI) matrix and all associated data (e.g. annotations, labels, ...) where can I find that? There is no path `.../fmri/regr/...` in neither `AIDAmri` nor `AIDAconnect` test data nor their respective repositories.

**Comment by aswendtlab-admin** [comment]
Try https://gin.g-node.org/aswendtlab/AIDAconnect_test_data/src/master/MRI_proc_data/P7/Control/GV_T3_14_1_1_3_20190821_095620/fMRI/regr/MasksTCs.GV.txt.mat

**Comment by THinnerichs** [comment]
That is terrific! Thank you very much! 
Two more questions regarding those matrices, as I would like to include them in our research:
1. Why are these matrices shaped `structures \times 100`? Is it just some embedding for each structure to generate the actual connectivity through e.g. PCA or some other similarity measurement?
2. What are the values in these matrices actually measuring? :)

Sorry for the rather naive questions.

**Comment by aswendtlab-admin** [comment]
In case of (rs-)fMRI the matrix is generated using FSLnets (https://github.com/ahheckel/FSL-scripts/blob/master/rsc/scripts/bin/FSLNets/nets_netmats.m). The file contains the time series (of the BOLD signal), 100 repetitions, for each of the 98 (49 per hemisphere) brain regions.

**Comment by THinnerichs** [comment]
I am still missing one step here. 
`net_netmats.m` states that it returns a netmat/matrix of form `(runs/subjects) \times (netmat elements)` with connectivity matrix flattened for each row, such that
> So for 20 subjects and 10 nodes, netmat will be 20x10^2 = 20x100

But as you claim you return `(run/subjects) \times regions` you probably used the `'amp'` method of that very function.

On the other hand `getMergedFMRI_data.m` performs no pre-processing on that output but rather takes precomputed connectivities to run them through `BCT`'s analysis functions. If I want to derive such pairwise correlations between each pair of regions how do I achieve that? :)

Feel free to correct me if I misunderstood you here.

**Comment by aswendtlab-admin** [comment]
We use a modified version of net_netmats.m => net_netmats_md.m und getMergedFMRI_data.m will use matrixMaker_rsfMRI.m to generate the correlations and reshape the netmats output to our desired structure. 
matrixMaker_rsfMRI.m in lines:
(35) netmats = nets_netmats_md(ts,0,0,'corr');
(37) mNet = reshape(netmats(1,:),[sqrt(length(netmats)) sqrt(length(netmats))]);  
If you process the data with AIDAconnect you can retrieve correlations between two regions e.g. by plotConnectionWeight.m.

**Comment by THinnerichs** [comment]
Thank you for the detailed answer.
Unfortunately, `net_netmats_md.m` seems to be neither part of your project nor any of the other mentioned ones. Could you please clarify? :)

**Comment by aswendtlab-admin** [comment]
Indeed, during the upload process, we forgot the modified FSL scripts. It is now included in the folder Tools.

**Comment by THinnerichs** [comment]
This worked beautifully. Thank you once more, also for the quick replies! :)

Could you also clarify whether the baseline measurement was done pre-stroke?

**Comment by aswendtlab-admin** [comment]
Sounds good! Baseline was pre-stroke.
